# This is a basic workflow that is manually triggered

name: Update All Nodes

on:
  schedule:
    - cron: '0 */1 * * *'

jobs:
  run-all:
    name: Run All
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./node/dev/requirements.txt
      - name: Run
        run: |
          python ./node/dev/run_all.py
      - name: Run All
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "Automated commit - schedule run"
          git push
      
      - name: Commit Changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update documentation"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
