# This is a basic workflow that is manually triggered

name: Update All Nodes

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 */1 * * *'
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Set Timezone
        run: sudo timedatectl set-timezone 'Asia/Tehran'
      - name: Install Requirements
        run: |
          pip install -r ./node/dev/requirements.txt
      - name: Running Tasks
        run: |
          python ./node/dev/run_all.py
          
      - name: Commit Changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: "GitHub Actions"
          author_email: "actions@github.com"
          message: "Update Nodes"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
